version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
#    volumes:
#      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --reload

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
#    volumes:
#      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend